name: Deploy to Staging

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Type check
        run: npm run type-check

      - name: Deploy to Cloudflare Workers (Staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            echo "*** Running pre-deploy commands ***"
            npm run cf-typegen
          command: deploy --env staging
        env:
          # Zendesk configuration (staging)
          ZENDESK_SUBDOMAIN: ${{ secrets.STAGING_ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.STAGING_ZENDESK_EMAIL }}
          ZENDESK_API_KEY: ${{ secrets.STAGING_ZENDESK_API_KEY }}
          # GitHub OAuth configuration (staging)
          GITHUB_CLIENT_ID: ${{ secrets.STAGING_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.STAGING_GITHUB_CLIENT_SECRET }}
          GITHUB_REDIRECT_URL: ${{ secrets.STAGING_GITHUB_REDIRECT_URL }}

      - name: Comment PR with deployment URL
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const comment = `🚀 **Staging deployment successful!**
            
            Your changes have been deployed to the staging environment.
            
            Please test your changes before merging to main.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });